# Generated by Django 5.1.6 on 2025-02-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stocklog_difference_stocklog_percentage_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='company',
            field=models.CharField(default='DefaultCompany', max_length=50),
        ),
    ]
