# Generated by Django 5.1.6 on 2025-02-22 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stocklog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
